server:
  port: 8080


sample:
  zipkin:
    enabled: false

spring:
  application:
    name: zip
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://localhost:9411/
